src/accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [    
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^register/$', views.register_view, name="register"),
    url(r'^passwordchange/$',views.passwordchange,name="passwordchange"),
]

src/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework_jwt.views import obtain_jwt_token

from accounts import views as account

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url转为各个app下的urls.py include下来
    # url(r'^login/', account.login_view, name="login"),
    # url(r'^logout/', account.logout_view, name="logout"),
    # url(r'^register/', account.register_view, name="register"),
    # url(r'^passwordchange/',account.passwordchange,name="passwordchange"),
    url(r'',include("accounts.urls")),

    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/posts/', include("posts.api.urls", namespace="posts-api")),
    url(r'^api/comments/', include("comments.api.urls", namespace="comments-api")),
    url(r'^api/users/', include("accounts.api.urls", namespace="users-api")),
    url(r'^', include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name="list"),
    url(r'^create/$', views.post_create, name="create"),
    url(r'^(?P<pk>[0-9]+)/$', views.post_detail, name="detail"),
    url(r'^(?P<pk>[\w-]+)/edit/$', views.post_update, name="update"),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.post_delete, name="delete"),
]

src/templates/base-bk.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}Blog{% endblock head_title %}</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"
          integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css"
          integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

    <link type="text/css" rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block head_extra %}{% endblock head_extra %}
</head>
<body>
    <div id="fb-root"></div>

    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url "posts:list" %}">Home</a></li>
            {% block post_detail_link %}
            {% endblock %}
        
            {% if not request.user.is_authenticated %}
            <li class="pull-right"><a href="{% url "register" %}">Register</a></li>
            <li class="pull-right"><a href="{% url "login" %}">Login</a></li>
            {% else %}
           
            <li class="pull-right"> 
                <a href="{% url "logout" %}">Logout</a>
            </li>
			<li class ="pull-right"><a href="{% url "passwordchange" %}">Changepassword</a></li>
            <span style="float: right; margin-right: 5px">
                Logged in as: <b>{{ request.user }}</b> 
            </span>
            {% endif %}
        </ol>
        {% include "messages_display.html" %}
        {% block content %}
        {% endblock content %}
    </div>

    <!-- JQuery -->
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>

    <!-- Bootstrap -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"
            integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

    <!-- Markdown -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js"></script>

    <!-- Magnific Popup (form picture zoom) -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js" type="text/javascript"></script>

    <!-- Custom -->
    {% block extra_footer %}
    {% endblock extra_footer %}
</body>
</html>

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <title>{% block head_title %}iBlog{% endblock head_title %}</title>

     {% block styles %}
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{% static 'libs/adminlte/2.3.11/bootstrap/css/bootstrap.min.css' %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'libs/font-awesome/4.7.0/css/font-awesome.min.css' %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{% static 'libs/ionicons/2.0.1/css/ionicons.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'libs/adminlte/2.3.11/dist/css/AdminLTE.min.css' %}">
    {% endblock styles %}

    {% block head_extra %}{% endblock head_extra %}
</head>
{% block page_body %}
<body>


    <div id="fb-root"></div>

    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url "posts:list" %}">Home</a></li>
            {% block post_detail_link %}
            {% endblock %}
        
            {% if not request.user.is_authenticated %}
            <li class="pull-right"><a href="{% url "register" %}">Register</a></li>
            <li class="pull-right"><a href="{% url "login" %}">Login</a></li>
            {% else %}
           
            <li class="pull-right"> 
                <a href="{% url 'accounts:logout' %}">Logout</a>
            </li>
			<li class ="pull-right"><a href="{% url 'accounts:passwordchange' %}">Changepassword</a></li>
            <span style="float: right; margin-right: 5px">
                Logged in as: <b>{{ request.user }}</b> 
            </span>
            {% endif %}
        </ol>
        {% include "messages_display.html" %}
        {% block content %}
        {% endblock content %}
    </div>



    {% block scripts %}
    <script src="{% static 'libs/adminlte/2.3.11/plugins/jQuery/jquery-2.2.3.min.js' %}"></script>
    <script src="{% static 'libs/adminlte/2.3.11/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'libs/vue/vue.js' %}"></script>
    {% endblock scripts %}

    <!-- Custom -->
    {% block extra_footer %}
    {% endblock extra_footer %}
</body>
{% endblock page_body %}
</html>

src/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_title %}{{ title }} |  {{ block.super }}{% endblock head_title %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        <h1 style="margin-top: 10px">{{ title }}</h1>
        <hr>
        <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
            {{ form | crispy }}
            <input class="btn btn-primary" type="submit" value="{{ title }}">
        </form>
    </div>
{% endblock content %}

src/templates/messages_display.html
 {% if messages %}
    {% for message in messages %}
         <div class="
            {% if message.tags == "success" %}
                alert alert-success
            {% elif message.tags == "error" %}
                alert alert-danger
            {% endif %}" style="text-align: center">
            <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
        </div>
    {% endfor %}
{% endif %}