src/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework_jwt.views import obtain_jwt_token

from accounts import views as account

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url转为各个app下的urls.py include下来
    # url(r'^login/', account.login_view, name="login"),
    # url(r'^logout/', account.logout_view, name="logout"),
    # url(r'^register/', account.register_view, name="register"),
    # url(r'^passwordchange/',account.passwordchange,name="passwordchange"),
    url(r'',include("accounts.urls")),

    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/posts/', include("posts.api.urls", namespace="posts-api")),
    url(r'^api/comments/', include("comments.api.urls", namespace="comments-api")),
    url(r'^api/users/', include("accounts.api.urls", namespace="users-api")),
    url(r'^', include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/comments/api/urls.py
from django.conf.urls import url
from .views import (
    CommentListAPIView,
    CommentDetailAPIView,
    CommentCreateAPIView,
)

urlpatterns = [
    url(r'^$', CommentListAPIView.as_view(), name="list"),
    url(r'^create/', CommentCreateAPIView.as_view(), name="create"),
    url(r'^(?P<id>\d+)/$', CommentDetailAPIView.as_view(), name="detail"),  # also update, delete
]

src/comments/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<id>\d+)/$', views.comment_thread, name="comment_thread"),
    url(r'^(?P<id>\d+)/delete/$', views.comment_delete, name="comment_delete"),
]

src/comments/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


class CommentManager(models.Manager):
    def all(self):
        return super(CommentManager, self).filter(parent=None)

    def filter_by_instance(self, instance):
        content_type = ContentType.objects.get_for_model(instance.__class__)
        obj_id = instance.id
        return super(CommentManager, self).filter(content_type=content_type, object_id=obj_id).filter(parent=None)

    def create_by_model_type(self, model_type, slug, content, user, parent_object=None):
        model_qs = ContentType.objects.filter(model=model_type)
        if model_qs.exists():
            some_model = model_qs.first().model_class()
            obj_qs = some_model.objects.filter(slug=slug)
            if obj_qs.exists() and obj_qs.count() == 1:
                instance = self.model()
                instance.content = content
                instance.user = user
                instance.content_type = model_qs.first()
                instance.object_id = obj_qs.first().id
                if parent_object:
                    instance.parent = parent_object
                instance.save()
                return instance
        return None


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    # Normal foreign key for one post
    # post = models.ForeignKey(Post)

    # Generic foreign key -> advantage: see all available tables as foreign key
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    parent = models.ForeignKey("self", null=True, blank=True)

    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    objects = CommentManager()

    class Meta:
        ordering = ["-timestamp"]

    def __str__(self):
        return str(self.user.username)

    def get_absolute_url(self):
        return reverse("comments:comment_thread", kwargs={"id": self.id})

    def get_parent_url(self):
        return reverse("comments:comment_thread", kwargs={"id": self.parent.id})

    def children(self):  # replies to comments
        return Comment.objects.filter(parent=self)

    @property
    def is_parent(self):
        if self.parent is not None:
            return False
        return True

src/comments/forms.py
from django import forms


class CommentForm(forms.Form):
    content_type = forms.CharField(widget=forms.HiddenInput)
    object_id = forms.IntegerField(widget=forms.HiddenInput)
    # parent_id = forms.IntegerField(widget=forms.HiddenInput, required=False)
    content = forms.CharField(label='', widget=forms.Textarea)

src/comments/api/views.py
from django.db.models import Q
from rest_framework.generics import (
    CreateAPIView, ListAPIView, RetrieveAPIView,
)
from rest_framework.mixins import DestroyModelMixin, UpdateModelMixin, CreateModelMixin
from rest_framework.filters import (
    SearchFilter, OrderingFilter
)
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from comments.models import Comment
from posts.api.permissions import IsOwnerOrReadOnly
from .serializers import CommentListSerializer, CommentDetailSerializer, create_comment_serializer


class CommentCreateAPIView(CreateAPIView):
    queryset = Comment.objects.all()

    def get_serializer_class(self):
        model_type = self.request.GET.get("type")
        slug = self.request.GET.get("slug")
        parent_id = self.request.GET.get("parent_id", None)

        return create_comment_serializer(model_type=model_type, slug=slug, parent_id=parent_id, user=self.request.user)


class CommentListAPIView(ListAPIView, CreateModelMixin):
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['content', 'user__first_name']
    serializer_class = CommentListSerializer
    # pagination_class = PostPageNumberPagination / enable if needed
    permission_classes = [IsAuthenticatedOrReadOnly]

    def get_queryset(self):
        queryset_list = Comment.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                Q(content__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)).distinct()
        return queryset_list


class CommentDetailAPIView(DestroyModelMixin, UpdateModelMixin, RetrieveAPIView):
    queryset = Comment.objects.filter(id__gte=0)
    serializer_class = CommentDetailSerializer
    lookup_field = "id"
    permission_classes = [IsOwnerOrReadOnly]

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

src/comments/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect, Http404
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import Comment
from .forms import CommentForm


@login_required
def comment_thread(request, id):
    try:
        obj = Comment.objects.get(id=id)
    except ObjectDoesNotExist:
        raise Http404

    initial_data = {
        "content_type": obj.content_type,
        "object_id": obj.object_id
    }

    form = CommentForm(request.POST or None, initial=initial_data)
    if form.is_valid():
        c_type = form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        object_id = form.cleaned_data.get("object_id")
        content_data = form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except (ValueError, TypeError):
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=object_id,
            content=content_data,
            parent=parent_obj
        )
        messages.success(request, "Reply was successfully saved")
        return HttpResponseRedirect(new_comment.get_parent_url())

    context = {
        "comment": obj,
        "form": form,
    }
    return render(request, "comment_thread.html", context)


@login_required
def comment_delete(request, id):
    try:
        obj = Comment.objects.get(id=id)
    except ObjectDoesNotExist:
        raise Http404

    if obj.user != request.user:
        # response = HttpResponse("You don't have the permissions to delete this comment")
        # response.status_code = 403
        # return response
        messages.error(request, "You don't have the permissions to delete this comment")
        return HttpResponseRedirect(obj.get_absolute_url())

    if request.method == "POST":
        url = obj.content_object.get_absolute_url()
        obj.delete()
        messages.success(request, "The comment \"{}\" has been successfully deleted".format(obj.content))

        if not obj.is_parent:
            return HttpResponseRedirect(obj.get_parent_url())
        return HttpResponseRedirect(url)

    return render(request, "confirm_delete.html", {"obj": obj})

src/comments/templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block head_title %}{{ instance.title }} |  {{ block.super }}{% endblock head_title %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        <p style="font-size: 20px; margin-top: 10px">{{ comment.content }}
            <a href="{% url "comments:comment_delete" id=comment.id %}" class="btn btn-danger" style="float: right">Delete</a>
            <a href="{% url "posts:detail" slug=comment.content_object.slug %}" class="btn btn-primary" style="float: right; margin-right: 5px">Back</a>
        </p>

        <footer>
            From: {{ comment.user }} |  {{ comment.timestamp|timesince }} ago |
            {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s
            {% endif %}{% endif %}
        </footer>
        <hr>
        <div style="margin-bottom: 20px">
            {% for child_comment in comment.children %}
                <blockquote>
                    <p>{{ child_comment.content }}</p>
                    <footer>
                        From: {{ child_comment.user }} |  {{ child_comment.timestamp|timesince }} ago |
                        {% if request.user == child_comment.user %}
                            <a href="{% url "comments:comment_delete" id=child_comment.id %}">Delete</a>
                        {% endif %}
                    </footer>
                </blockquote>
            {% endfor %}
            <form method="POST" action="">{% csrf_token %}
                {{ form | crispy }}
                <input type="hidden" name="parent_id" value="{{ comment.id }}">
                <input type="submit" value="Reply" class="btn btn-default">
            </form>
        </div>
    </div>
{% endblock content %}

src/comments/templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}

{% block head_title %}{{ instance.title }} |  {{ block.super }}{% endblock head_title %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        <h1>Confirm Delete</h1>
        <form method="POST" action="">{% csrf_token %}
            <p>Are you sure you want to delete: {{ obj.content }} ?</p>
            <input type="submit" value="Confirm" class="btn btn-danger">
            <a href="{{ obj.get_absolute_url }}" class="btn btn-default">Cancel</a>
        </form>
    </div>
{% endblock content %}