src/blog/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework_jwt.views import obtain_jwt_token

from accounts import views as account

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url转为各个app下的urls.py include下来
    # url(r'^login/', account.login_view, name="login"),
    # url(r'^logout/', account.logout_view, name="logout"),
    # url(r'^register/', account.register_view, name="register"),
    # url(r'^passwordchange/',account.passwordchange,name="passwordchange"),
    url(r'',include("accounts.urls")),

    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/posts/', include("posts.api.urls", namespace="posts-api")),
    url(r'^api/comments/', include("comments.api.urls", namespace="comments-api")),
    url(r'^api/users/', include("accounts.api.urls", namespace="users-api")),
    url(r'^', include("posts.urls", namespace="posts")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/api/urls.py
from django.conf.urls import url
from .views import PostListAPIView, PostDetailAPIView


urlpatterns = [
    url(r'^$', PostListAPIView.as_view(), name="list"),  # also create
    url(r'^(?P<slug>[\w-]+)/$', PostDetailAPIView.as_view(), name="detail"),  # also update and delete
]

src/posts/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name="list"),
    url(r'^create/$', views.post_create, name="create"),
    url(r'^(?P<pk>[0-9]+)/$', views.post_detail, name="detail"),
    url(r'^(?P<pk>[\w-]+)/edit/$', views.post_update, name="update"),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.post_delete, name="delete"),
]

src/posts/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.conf import settings
# -*- coding:utf-8 -*-
from django.core.urlresolvers import reverse
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from markdown_deux import markdown
from .utils import get_read_time
import unicodedata
from unidecode import unidecode

class PostManager(models.Manager):
    def active(self, *args, **kwargs):
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())


def upload_location(instance, file_name):
    today = timezone.now()
    year = today.year
    month = today.month
    day = today.day
    return "user_{user_id}/{year}/{month}/{day}/{file}".format(
        user_id=instance.user.id, year=year, month=month, day=day, file=file_name)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1)
    title = models.CharField(max_length=120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location, null=True, blank=True,
                              width_field="width_field", height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default=False)
    publish = models.DateField(auto_now=False, auto_now_add=False)
    read_time = models.TimeField(null=True, blank=True)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    objects = PostManager()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:detail", kwargs={"pk": self.pk})

    def get_api_url(self):
        return reverse("posts-api:detail", kwargs={"pk": self.pk})

    def get_markdown(self):
        return mark_safe(markdown(self.content))

    @property
    def get_content_type(self):
        return ContentType.objects.get_for_model(self.__class__)

    class Meta:
        ordering = ["-timestamp", "-updated"]


def create_slug(instance, new_slug=None):
    u = unicode(unidecode(instance.title))
    slug = slugify(u)
    if new_slug is not None:
        
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        new_slug = "{}-{}".format(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug


def pre_save_post_receiver(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

    if instance.content:
        read_time = get_read_time(instance.get_markdown())
        instance.read_time = read_time

pre_save.connect(pre_save_post_receiver, sender=Post)

src/posts/forms.py
from django import forms
from django.forms.extras.widgets import SelectDateWidget
from django.utils import timezone
from pagedown.widgets import PagedownWidget
from .models import Post


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=PagedownWidget(show_preview=False))
    publish = forms.DateField(widget=forms.SelectDateWidget, initial=timezone.now())

    class Meta:
        model = Post
        fields = [
            "title",
            "content",
            "image",
            "draft",
            "publish",
        ]

src/posts/api/views.py
from django.db.models import Q
from rest_framework.generics import (
    ListAPIView, RetrieveAPIView
)
from rest_framework.filters import (
    SearchFilter, OrderingFilter
)
from rest_framework.mixins import DestroyModelMixin, UpdateModelMixin, CreateModelMixin
from rest_framework.permissions import IsAuthenticatedOrReadOnly

from posts.models import Post
from .serializers import PostListSerializer, PostDetailSerializer
from .permissions import IsOwnerOrReadOnly


class PostListAPIView(ListAPIView, CreateModelMixin):
    serializer_class = PostListSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ['title', 'content', 'user__first_name']
    # pagination_class = PostPageNumberPagination / enable if needed
    permission_classes = [IsAuthenticatedOrReadOnly]

    def get_queryset(self):
        queryset_list = Post.objects.all()
        query = self.request.GET.get("q")
        if query:
            queryset_list = queryset_list.filter(
                Q(title__icontains=query) |
                Q(content__icontains=query) |
                Q(user__first_name__icontains=query) |
                Q(user__last_name__icontains=query)).distinct()
        return queryset_list

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)

    def post(self, request, *args, **kwargs):
        return self.create(request, args, kwargs)


class PostDetailAPIView(RetrieveAPIView, DestroyModelMixin, UpdateModelMixin):
    queryset = Post.objects.all()
    serializer_class = PostDetailSerializer
    permission_classes = [IsOwnerOrReadOnly]
    lookup_field = "slug"

    def perform_update(self, serializer):
        serializer.save(user=self.request.user)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)

src/posts/views.py
# -*- coding:utf-8 -*-
# import sys
# reload(sys)
import sys
import imp
imp.reload(sys)
# sys.setdefaultencoding( "utf-8" )

import os
# from urllib import quote_plus
from urllib import parse
from django.conf import settings
from django.contrib import messages
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.shortcuts import render, get_object_or_404, redirect, Http404
from django.http import HttpResponseRedirect

from django.utils import timezone
from .models import Post
from .forms import PostForm
from comments.forms import CommentForm
from comments.models import Comment


@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfully created")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": "Form",
        "form": form,
    }
    return render(request, "post_form.html", context)


@login_required
def post_detail(request, pk=None):
    instance = get_object_or_404(Post, pk=pk)
    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    share_string = parse.quote_plus(str(instance.content))

    initial_data = {
        "content_type": instance.get_content_type,
        "object_id": instance.id
    }

    comment_form = CommentForm(request.POST or None, initial=initial_data)
    if comment_form.is_valid() and request.user.is_authenticated():
        c_type = comment_form.cleaned_data.get("content_type")
        content_type = ContentType.objects.get(model=c_type)
        object_id = comment_form.cleaned_data.get("object_id")
        content_data = comment_form.cleaned_data.get("content")
        parent_obj = None
        try:
            parent_id = int(request.POST.get("parent_id"))
        except (ValueError, TypeError):
            parent_id = None

        if parent_id:
            parent_qs = Comment.objects.filter(id=parent_id)
            if parent_qs.exists() and parent_qs.count() == 1:
                parent_obj = parent_qs.first()

        new_comment, created = Comment.objects.get_or_create(
            user=request.user,
            content_type=content_type,
            object_id=object_id,
            content=content_data,
            parent=parent_obj
        )
        messages.success(request, "Comment was successfully saved")
        return HttpResponseRedirect(new_comment.content_object.get_absolute_url())

    comments = Comment.objects.filter_by_instance(instance)

    context = {
        "title": "Detail view",
        "instance": instance,
        "share_string": share_string,
        "comments": comments,
        "comment_form": comment_form,
    }
    return render(request, "post_detail.html", context)


@login_required
def post_list(request):
    today = timezone.now().date()
    queryset_list = Post.objects.active()
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(title__icontains=query) |
            Q(content__icontains=query) |
            Q(user__first_name__icontains=query) |
            Q(user__last_name__icontains=query)).distinct()

    paginator = Paginator(queryset_list, 3)
    page = request.GET.get('page')
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        queryset = paginator.page(1)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        "object_list": queryset,
        "title": "Blog",
        "today": today,
    }
    return render(request, "post_list.html", context)


@login_required
def post_update(request, pk=None):
    if not request.user.is_staff or not request.user.is_superuser:
        messages.error(request, "You don't have the permissions to delete this post")
        #raise Http404
        return redirect("posts:list")
    instance = get_object_or_404(Post, pk=pk)
    form = PostForm(request.POST or None, request.FILES or None, instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        messages.success(request, "Successfully updated")
        return HttpResponseRedirect(instance.get_absolute_url())

    context = {
        "title": "Edit view",
        "instance": instance,
        "form": form,
    }
    return render(request, "post_form.html", context)


@login_required
def post_delete(request, pk=None):
    if not request.user.is_staff or not request.user.is_superuser:
        messages.error(request, "You don't have the permissions to delete this post")
        #raise Http404
        return redirect("posts:list")

    instance = get_object_or_404(Post, pk=pk)

    os.remove(instance.image.path)
    __folder_cleanup(os.path.dirname(instance.image.path))

    instance.delete()

    messages.success(request, "Successfully deleted")
    return redirect("posts:list")


def __folder_cleanup(path):
    """
    Removes all empty folders from path to settings.MEDIA_ROOT recursively

    This method starts in the path folder and checks if the folder is empty,
    if so it deletes it. After that it makes a recursive call with the parent directory of path
    and does the same. If at any point the function can't remove the directory it stops
    :param path: The path to start the recursion
    :return: None
    """
    if path == settings.MEDIA_ROOT:
        return
    try:
        ds_store = os.path.join(path, ".DS_Store")  # For MAC OS
        if os.path.exists(ds_store):
            os.remove(ds_store)
        os.rmdir(path)
    except OSError:
        return
    return __folder_cleanup(os.path.dirname(path))

src/posts/templates/post_detail.html
{% extends "base.html" %}
{% load urlify %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block head_title %}{{ instance.title }} |  {{ block.super }}{% endblock head_title %}

{% block post_detail_link %}
    <li><a href="{{ instance.get_absolute_url }}">{{ instance.title }}</a></li>
{% endblock %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        {% if instance.image %}
            <a class="image-popup" href="{{ instance.image.url }}">
                <img src="{{ instance.image.url }}" class="img-responsive detail-image">
            </a>
        {% endif %}
        <br>
        <a href="{% url 'posts:update' pk=instance.pk %}" class="btn btn-default" role="button">Edit</a>
        <a href="{% url 'posts:delete' pk=instance.pk %}" class="btn btn-danger delete-button" role="button">Delete</a>
        <a style="float: right" href="{% url 'posts:list' %}" class="btn btn-primary" role="button">Posts Overview</a>

        <h1>{{ instance.title }} <small>{% if instance.draft %}<span style="color: red">Draft</span> {% endif %}{{ instance.publish }}<br></small></h1>
        {% if instance.user %}
            <p style="font-weight: 300">Author: {{ instance.user.username }}</p>
        {% endif %}
        <p>{% if instance.read_time %}Read time: {{ instance.read_time| time:"i" }} minutes{% endif %}</p>

        <p><div class="fb-like" data-href="{{ request.build_absolute_uri }}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div></p>
        <p>
            <a href="https://www.facebook.com/sharer/sharer.php?u={{ request.build_absolute_uri }}">
            Facebook
            </a>
            <a href="https://twitter.com/home?status={{ share_string | truncatechars:80 }}%20{{ request.build_absolute_uri }}">
            Twitter
            </a>
            <a href='https://plus.google.com/share?url={{ request.build_absolute_uri }}'>Google Plus</a>
            
            <a href="http://www.reddit.com/submit?url={{ request.build_absolute_uri }}&title={{ share_string }}">Reddit</a>
        </p>
        <hr>

        <div class="content-markdown">
            {{ instance.get_markdown }}
        </div>

        <hr style="border: 1px solid #afb0af;">
        <div style="margin-bottom: 20px">
            <p class="lead">Comments</p>
            {% if request.user.is_authenticated %}
            <form method="POST" action="">{% csrf_token %}
                {{ comment_form | crispy }}
                <input type="submit" value="Comment" class="btn btn-default">
            </form>
            <hr>
            {% for comment in comments %}
                <blockquote>
                    <p>{{ comment.content }}</p>
                    <footer>
                        From: {{ comment.user }} |  {{ comment.timestamp|timesince }} ago |
                        {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s
                        {% endif %} | {% endif %}
                        <a class="comment-reply-btn" href="#">Reply</a> |
                        <a href="{{ comment.get_absolute_url }}">Thread</a>
                    </footer>

                    <div class="comment-reply">
                        {% for child_comment in comment.children %}
                            <blockquote>
                                <p>{{ child_comment.content }}</p>
                                <footer>From: {{ child_comment.user }} |  {{ child_comment.timestamp|timesince }} ago</footer>
                            </blockquote>
                        {% endfor %}
                        <form method="POST" action="">{% csrf_token %}
                            {{ comment_form | crispy }}
                            <input type="hidden" name="parent_id" value="{{ comment.id }}">
                            <input type="submit" value="Reply" class="btn btn-default">
                        </form>
                    </div>
                </blockquote>
                <hr>
            {% endfor %}
            {% else %}
                <p>You must login to comment</p>
            {% endif %}
        </div>
    </div>
{% endblock content %}

{% block extra_footer %}
    <script src="{% static 'js/scripts.js'%}" type="text/javascript"></script>
{% endblock extra_footer %}

src/posts/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load staticfiles %}

{% block head_extra %}
    {{ form.media }}
{% endblock head_extra %}

{% block content %}
    <div class="col-sm-6">
        <h1>Preview</h1>
        <hr>
        <div class="content-preview">
            <h3 id="preview-title"></h3><br>
            <p id="preview-content"></p>
        </div>
    </div>
    <div class="col-sm-6">
        <h1>{{ title }}</h1>
        <hr>
        <form method="POST" action="" enctype="multipart/form-data">{% csrf_token %}
            {{ form | crispy }}
            <input class="btn btn-primary" type="submit"
                   value="{% if request.path == "/create/" %} Create {% else %} Update {% endif %}">
        </form>
    </div>
{% endblock content %}

{% block extra_footer %}
    <script src="{% static 'js/markdown.js'%}" type="text/javascript"></script>
{% endblock extra_footer %}

src/posts/templates/post_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
    <div class="col-sm-6 col-sm-offset-3">
        <h1 style="margin-bottom: 20px; margin-top: 0">{{ title }}</h1>
        <form method="GET" action="" class="row">
            <div class="col-sm-6">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search Posts" value="{{ request.GET.q }}">
                    <span class="input-group-btn">
                        <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                    </span>
                </div>
            </div>
            <div style="float: right; margin-right: 15px">
                <a href="{% url 'posts:create' %}" class="btn btn-info">Create Post</a>
            </div>
        </form><br>

        {% if not object_list %}
            <p style="margin-bottom: 0; color: red; font-weight: bold">
                There are no uploaded posts. Be the first :-)
            </p>
        {% endif %}

        {% for obj in object_list %}
            <div class="row">
                <div class="col-sm-12">
                    <div class="thumbnail">
                        {% if obj.image %}
                            <a class="image-popup" href="{{ obj.image.url }}" title="{{ obj.title }}">
                                <img src="{{ obj.image.url }}" class="img-responsive">
                            </a>
                        {% endif %}
                        <div class="caption">
                            {% if obj.draft %}<h3>Staff only: Draft {% if obj.publish > today %}<h3>Staff only: Future Post</h3> {% endif %}</h3>{% endif %}
                            <h3><a href="{{ obj.get_absolute_url }}">{{ obj.title }}</a> <small>{{ obj.timestamp | timesince }} </small></h3>
                            {% if obj.user %}<p style="font-weight: 300">Author: {{ obj.user.username }}</p>{% endif %}
                            <hr style="margin-top: 15px">
                            <div class="content-markdown">{{ obj.get_markdown | truncatechars_html:120 }}</div>
                            <p style="margin-top: 25px"><a href="{{ obj.get_absolute_url }}" class="btn btn-primary" role="button">View</a></p>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

        <div class="pagination">
            <span class="step-links">
                {% if object_list.has_previous %}
                    <a href="?page={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a>
                {% endif %}

                <span class="current">
                    Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}
                </span>

                {% if object_list.has_next %}
                    <a href="?page={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a>
                {% endif %}
            </span>
        </div>
    </div>
{% endblock content %}

{% block extra_footer %}
    <script src="{% static 'js/scripts.js'%}" type="text/javascript"></script>
{% endblock extra_footer %}